name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          lein: 2.9.1
      - name: Get leiningen version
        run: lein -v
      - name: Get leiningen version
        run: lein run -m simple_shift_reduce_parsing.core --help
      - name: Get leiningen version
        run: lein uberjar
